spring:
  datasource:
      url: jdbc:mysql://localhost:3306/carepay?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: password1
      driverClassName: com.mysql.cj.jdbc.Driver

logging:
    level:
        root: INFO
        org:
            springframework:
                security: ERROR
                web: DEBUG
        hibernate: DEBUG
        apache:
            commons:
                dbcp2: DEBUG